(define (problem trasporto-problema)
  (:domain trasporto)
    (:requirements :fluents)
  
  ;; Oggetti
  (:objects
    A B C D E F G H I J K L M N O P Q R S T U V W - location
  )
  
  ;; Stato iniziale
  (:init
    (at W)

    (= (total-cost) 0)

    (connected W E)
    (connected E W)
    (connected W A)
    (connected A W)
    (connected W B)
    (connected B W)
    (connected W C)
    (connected C W)
    (connected A Q)
    (connected Q A)
    (connected A R)
    (connected R A)
    (connected A F)
    (connected F A)
    (connected A B)
    (connected B A)
    (connected B J)
    (connected J B)
    (connected B H)
    (connected H B)
    (connected B G)
    (connected G B)
    (connected C K)
    (connected K C)
    (connected C J)
    (connected J C)
    (connected D E)
    (connected E D)
    (connected D K)
    (connected K D)
    (connected E N)
    (connected N E)
    (connected E Q)
    (connected Q E)
    (connected E P)
    (connected P E)
    (connected F G)
    (connected G F)
    (connected G S)
    (connected S G)
    (connected G H)
    (connected H G)
    (connected H T)
    (connected T H)
    (connected H I)
    (connected I H)
    (connected H J)
    (connected J H)
    (connected I U)
    (connected U I)
    (connected J V)
    (connected V J)
    (connected K N)
    (connected N K)
    (connected K L)
    (connected L K)
    (connected K V)
    (connected V K)
    (connected L M)
    (connected M L)
    (connected L N)
    (connected N L)
    (connected M O)
    (connected O M)
    (connected O P)
    (connected P O)
    (connected P Q)
    (connected Q P)
    (connected Q R)
    (connected R Q)
    (connected R S)
    (connected S R)
    (connected S T)
    (connected T S)
    (connected T U)
    (connected U T)
    (connected U V)
    (connected V U)

    (= (distance W E) 10)
    (= (distance E W) 10)
    (= (distance W A) 11)
    (= (distance A W) 11)
    (= (distance W B) 21)
    (= (distance B W) 21)
    (= (distance W C) 18)
    (= (distance C W) 18)
    (= (distance A Q) 9)
    (= (distance Q A) 9)
    (= (distance A R) 10)
    (= (distance R A) 10)
    (= (distance A F) 21)
    (= (distance F A) 21)
    (= (distance A B) 3)
    (= (distance B A) 3)
    (= (distance B J) 7)
    (= (distance J B) 7)
    (= (distance B H) 6)
    (= (distance H B) 6)
    (= (distance B G) 15)
    (= (distance G B) 15)
    (= (distance C K) 13)
    (= (distance K C) 13)
    (= (distance C J) 6)
    (= (distance J C) 6)
    (= (distance D E) 8)
    (= (distance E D) 8)
    (= (distance D K) 8)
    (= (distance K D) 8)
    (= (distance E N) 9)
    (= (distance N E) 9)
    (= (distance E Q) 17)
    (= (distance Q E) 17)
    (= (distance E P) 16)
    (= (distance P E) 16)
    (= (distance F G) 4)
    (= (distance G F) 4)
    (= (distance G S) 22)
    (= (distance S G) 22)
    (= (distance G H) 29)
    (= (distance H G) 29)
    (= (distance H T) 34)
    (= (distance T H) 34)
    (= (distance H I) 4)
    (= (distance I H) 4)
    (= (distance H J) 7)
    (= (distance J H) 7)
    (= (distance I U) 16)
    (= (distance U I) 16)
    (= (distance J V) 6)
    (= (distance V J) 6)
    (= (distance K N) 5)
    (= (distance N K) 5)
    (= (distance K L) 17)
    (= (distance L K) 17)
    (= (distance K V) 25)
    (= (distance V K) 25)
    (= (distance L M) 31)
    (= (distance M L) 31)
    (= (distance L N) 9)
    (= (distance N L) 9)
    (= (distance M O) 10)
    (= (distance O M) 10)
    (= (distance O P) 8)
    (= (distance P O) 8)
    (= (distance P Q) 13)
    (= (distance Q P) 13)
    (= (distance Q R) 8)
    (= (distance R Q) 8)
    (= (distance R S) 6)
    (= (distance S R) 6)
    (= (distance S T) 5)
    (= (distance T S) 5)
    (= (distance T U) 7)
    (= (distance U T) 7)
    (= (distance U V) 8)
    (= (distance V U) 8)

  )
  
  ;; Obiettivi
  (:goal (and
            (at W) 
            (delivered H)
            (delivered A)
            (delivered O)
            (delivered J)
            (delivered K)                    
       )
  )
  (:metric minimize (total-cost))
)
